version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017" 
  frontend:
    build: ./frontend
    stdin_open: true 
    tty: true
    environment:
      REACT_APP_DB_URL: "mongodb://mongodb:27017/klaster"
      REACT_APP_LOGIN_URL: "http://localhost:3001/api/login"
      REACT_APP_REG_URL: "http://localhost:3001/api/signup"
      REACT_APP_EVENTS_URL: "http://localhost:3002/api/getall"
    ports:
      - "3000:3000"
    depends_on:
      - user-auth
      - catalog
      - rezervacija
  user-auth:
    build: ./user-auth
    ports:
      - "3001:3030"
    environment:
      DB_URL: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
  catalog:
    build: ./catalog
    ports:
      - "3002:8080"
    depends_on:
      - mongodb
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
  rezervacija:
    build: ./rezervacija
    ports:
      - "3003:3300"
    environment:
      RAB_URL: "amqp://rabbitmq:5672"
    depends_on:
      - rabbitmq
  naracka:
    build: ./naracka
  
  
