apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
  labels:
    app: rezervacija-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservacija
  template:
    metadata:
      labels:
        app: rezervacija
    spec:
      containers:
        - name: user-auth
          image: klasterproekt_user-auth
          ports:
           - containerPort: 3030
          imagePullPolicy: Never
          env:
          - name: DB_URL
            value: "mongodb://mongodb-service:27017/klaster"
