apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
  labels:
    app: user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: klasterproekt_user-auth
          ports:
           - containerPort: 3001
          imagePullPolicy: Never
