apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:  
        claimName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          volumeMounts:
          - name: mongodb-data
            mountPath: /data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
